# Generated by Django 3.0.2 on 2020-04-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200412_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='batch',
            field=models.ManyToManyField(blank=True, to='posts.Batch'),
        ),
    ]
