# Generated by Django 3.0.2 on 2020-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200412_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='batch',
        ),
        migrations.AddField(
            model_name='category',
            name='seasons',
            field=models.CharField(blank=True, choices=[('Y', 'Year'), ('S', 'Semester')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='semesters',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='years',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
