# Generated by Django 3.0.2 on 2020-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200412_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seasons',
            field=models.CharField(blank=True, choices=[('Y', 'Year'), ('S', 'Semester')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='semesters',
            field=models.CharField(blank=True, default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='years',
            field=models.CharField(blank=True, default=1, max_length=1),
            preserve_default=False,
        ),
    ]
