# Generated by Django 3.0.2 on 2020-04-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200412_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesters', models.CharField(blank=True, choices=[('1', '1st Sem'), ('2', '2nd Sem'), ('3', '3rd Sem'), ('4', '4th Sem'), ('5', '5th Sem'), ('6', '6th Sem'), ('7', '7th Sem'), ('8', '8th Sem')], max_length=1)),
                ('years', models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='category',
            name='years',
        ),
    ]
