# Generated by Django 3.0.6 on 2020-08-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_batch_slug'),
        ('users', '0006_auto_20200519_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.Batch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.Category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='boy.png', null=True, upload_to='profile_pics'),
        ),
    ]
