# Generated by Django 3.0.2 on 2020-04-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('seasons', models.CharField(blank=True, choices=[('Y', 'Year'), ('S', 'Semester')], max_length=1)),
                ('batches', models.ManyToManyField(blank=True, to='faculty.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('slug', models.SlugField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Batch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Category')),
            ],
        ),
    ]
