# Generated by Django 3.0.2 on 2020-04-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20200415_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
