# Generated by Django 3.0.6 on 2020-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20200416_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
